### ISSUE TITLE
Not walet, it's Wallet

### ISSUE THREAD

**Issue by tomo0611** [komugi-mcbe/Menu#2]
名前空間に"walet"という単語が含まれているようですが、序にwaletは呑み込むという意味です。
なのでwalletに修正してください！
![vlcsnap-2020-06-07-14h21m54s099](https://user-images.githubusercontent.com/31959526/84566952-3d267000-adb0-11ea-80e7-0fcf43e79b03.png)

**Comment by xtakumatutix** [comment]
ありがとうございます。
修正され次第、閉じます
